# docker run -p 5000:80 -v "$(pwd)"/src:/var/www/html/ -d hello-php
# docker build -t hello-php .
# ubicado en directorio php: docker run -p 5000:80 -v "$(pwd)"/src:/var/www/html/ -d hello-php
FROM php:7.4-apache

#COPY /src /var/www/html

EXPOSE 80
